version: "3.8"

services:
  backend:
    host_name: django
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DJANGO_WORKDIR=${DJANGO_WORKDIR}
        - DEBUG=${DJANGO_DEBUG}
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./db:/db
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - DEBUG=${DJANGO_DEBUG}
