version: "3.9"
volumes:
  postgres_data:


services:
  #
  # ------------------------------------------------------------------
  #
  db:
    image: postgres:15-alpine
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  #
  # ------------------------------------------------------------------
  #
  pgadmin:
    image: dpage/pgadmin4
    expose:
      - 80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "$PWD/db/servers.json:/pgadmin4/servers.json"
      - "$PWD/db/pgpass:/pgpass"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fst-pgadmin.rule=Host(`fst-pgadmin.localhost`)"
  #
  # ------------------------------------------------------------------
  #
  backend:
    hostname: django
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DJANGO_WORKDIR=${DJANGO_WORKDIR}
        - DEBUG=${DJANGO_DEBUG}
    volumes:
      - $PWD/fst_backend:${DJANGO_WORKDIR}/fst_backend
    expose:
      - 8000
    environment:
      - DEBUG=${DJANGO_DEBUG}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_WORKDIR=${DJANGO_WORKDIR}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fst-backend.rule=Host(`fst-backend.localhost`)"
  #
  # ------------------------------------------------------------------
  #
  traefik:
    image: traefik:2.10
    ports:
      - 8000:80
      - 8001:8080
    volumes:
      - $PWD/traefik/traefik.dev.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

#
# ------------------------------------------------------------------
#
