version: "3.9"

services:
  db:
    image: postgres:15-alpine
    host_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  backend:
    host_name: django
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DJANGO_WORKDIR=${DJANGO_WORKDIR}
        - DEBUG=${DJANGO_DEBUG}
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./db:/db
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - DEBUG=${DJANGO_DEBUG}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"

  traefik:
    image: traefik:2.10
    ports:
      - 8000:80
      - 8001:8080
    depends_on:
      - backend
    volumes:
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
