# Generated by Django 4.2.4 on 2023-08-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_allergies_allergy"),
        ("accounts", "0002_remove_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.member",
            ),
        ),
    ]
