# Generated by Django 4.2.6 on 2023-10-10 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fst_backend.api.models.eventmedia
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('nuts', 'Nüsse'), ('lactose', 'Laktose'), ('sesame', 'Sesam'), ('fish', 'Fisch'), ('eggs', 'Eier'), ('gluten', 'Gluten'), ('mustard', 'Senf'), ('celery', 'Sellerie'), ('soy', 'Soja'), ('custom', 'Sonstige')], default='custom', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=64, null=True)),
                ('from_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_events', to='api.customdate')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('gender', models.CharField(choices=[('not_specified', '----'), ('male', 'Male'), ('female', 'Female'), ('diverse', 'Diverse')], max_length=15)),
                ('generation', models.CharField(choices=[('not_specified', '----'), ('yellow', 'yellow'), ('orange', 'orange'), ('green', 'green'), ('blue', 'blue'), ('red', 'Female'), ('violet', 'Diverse')], max_length=15)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('middlenames', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('placeOfBirth', models.CharField(blank=True, max_length=100, null=True)),
                ('placeOfDeath', models.CharField(blank=True, max_length=100, null=True)),
                ('placeholder', models.BooleanField(blank=True, null=True)),
                ('birthday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday_nodes', to='api.customdate')),
                ('deathday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathday_nodes', to='api.customdate')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='api.node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SpouseRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('partnership', 'partnership'), ('married', 'married')], max_length=16)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_spouse_node_set', to='api.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_spouse_node_set', to='api.node')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.CreateModel(
            name='SiblingRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('blood', 'blood'), ('half', 'half'), ('step', 'step')], max_length=10)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_sibling_node_set', to='api.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_sibling_node_set', to='api.node')),
            ],
            options={
                'unique_together': {('from_node', 'to_node')},
            },
        ),
        migrations.AddField(
            model_name='node',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='sibling_set', through='api.SiblingRelationship', to='api.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='spouse_set', through='api.SpouseRelationship', to='api.node'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('prof', 'Prof.'), ('dr', 'Dr.'), ('profDr', 'Prof. Dr.')], max_length=10, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('middlenames', models.CharField(blank=True, max_length=100, null=True)),
                ('birthname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('dietType', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan'), ('custom', 'Sonstige')], max_length=100, null=True)),
                ('placeOfBirth', models.CharField(blank=True, max_length=100, null=True)),
                ('placeOfDeath', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.ManyToManyField(blank=True, to='api.allergy')),
                ('birthday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday_members', to='api.customdate')),
                ('deathday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathday_members', to='api.customdate')),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mediaUrl', models.ImageField(blank=True, null=True, upload_to=fst_backend.api.models.eventmedia.upload_to)),
                ('mimeType', models.CharField(max_length=64)),
                ('from_day', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('from_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('from_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)])),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='to_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_events', to='api.customdate'),
        ),
    ]
