# Generated by Django 4.2.4 on 2023-08-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="from_date",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from",
                to="api.customedate",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="to_date",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_to",
                to="api.customedate",
            ),
        ),
    ]
