# Generated by Django 4.2.6 on 2023-10-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='from_day',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='from_month',
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='from_year',
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='from_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventmedia_froms', to='api.customdate'),
        ),
    ]
