# Generated by Django 4.2.4 on 2023-08-22 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_event_from_date_event_to_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="from_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="to_date",
        ),
        migrations.AddField(
            model_name="event",
            name="from_day",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="from_month",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(13),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="from_year",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="to_day",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="to_month",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(13),
                ],
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="to_year",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="CustomeDate",
        ),
    ]
