# Generated by Django 4.2.6 on 2023-10-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_eventmedia_from_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
