# Generated by Django 4.2.6 on 2023-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventmedia_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmedia',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='thumbnailUrl',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails/'),
        ),
    ]
