# Generated by Django 4.2.4 on 2023-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_tag_event_alter_event_from_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="api.tag"),
        ),
    ]
