# Generated by Django 4.2.4 on 2023-08-22 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_tag_event_event_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="to_year",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mediaUrl", models.CharField(max_length=1024)),
                ("mimeType", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
            ],
        ),
    ]
