# Generated by Django 4.2.7 on 2023-11-02 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customdate_day_alter_customdate_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdate',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
