# Generated by Django 4.2.7 on 2023-11-03 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_customdate_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdate",
            name="day",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(31)],
            ),
        ),
        migrations.AlterField(
            model_name="customdate",
            name="month",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(12)],
            ),
        ),
        migrations.AlterField(
            model_name="customdate",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
