# Generated by Django 4.2.4 on 2023-08-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_event_to_year_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmedia",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.event"
            ),
        ),
    ]
