# Generated by Django 4.2.4 on 2023-08-22 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_eventmedia_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmedia",
            name="from_month",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(13),
                ],
            ),
        ),
        migrations.AddField(
            model_name="eventmedia",
            name="from_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
