# Generated by Django 4.2.7 on 2023-11-03 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_customdate_day_alter_customdate_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentchildrelationship",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
