# Generated by Django 4.2.4 on 2023-08-22 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_eventmedia_from_month_eventmedia_from_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmedia",
            name="from_day",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="eventmedia",
            name="tags",
            field=models.ManyToManyField(to="api.tag"),
        ),
    ]
