# Generated by Django 4.2.7 on 2023-11-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_member_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="deathday",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deathday_members",
                to="api.customdate",
            ),
        ),
    ]
