# Generated by Django 4.2.4 on 2023-08-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_eventmedia_from_day_eventmedia_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmedia",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.event",
            ),
        ),
    ]
