# Generated by Django 4.2.4 on 2023-08-22 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_eventmedia_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("prof", "Prof."),
                            ("dr", "Dr."),
                            ("profDr", "Prof. Dr."),
                            ("none", ""),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=100, null=True)),
                ("lastname", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middlenames",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birthname", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("zip", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dietType",
                    models.CharField(
                        choices=[
                            ("vegetarian", "vegetarisch"),
                            ("vegan", "vegan"),
                            ("custom", "sonstige"),
                            ("none", ""),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "placeOfBirth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "placeOfDeath",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
