# Generated by Django 4.2.4 on 2023-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="dietType",
            field=models.CharField(
                choices=[
                    ("none", ""),
                    ("vegetarian", "Vegetarisch"),
                    ("vegan", "Vegan"),
                    ("custom", "Sonstige"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="lastname",
            field=models.CharField(default="LASTNAME", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", ""),
                    ("prof", "Prof."),
                    ("dr", "Dr."),
                    ("profDr", "Prof. Dr."),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
