# Generated by Django 4.2.4 on 2023-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_member_diettype_alter_member_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="dietType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vegetarian", "Vegetarisch"),
                    ("vegan", "Vegan"),
                    ("custom", "Sonstige"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("prof", "Prof."), ("dr", "Dr."), ("profDr", "Prof. Dr.")],
                max_length=10,
                null=True,
            ),
        ),
    ]
