# Generated by Django 4.2.4 on 2023-08-22 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_member_diettype_alter_member_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="dietType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vegetarian", "Vegetarisch"),
                    ("vegan", "Vegan"),
                    ("custom", "Sonstige"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Allergies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nuts", "Nüsse"),
                            ("lactose", "Laktose"),
                            ("sesame", "Sesam"),
                            ("fish", "Fisch"),
                            ("eggs", "Eier"),
                            ("gluten", "Gluten"),
                            ("mustard", "Senf"),
                            ("celery", "Sellerie"),
                            ("soy", "Soja"),
                            ("custom", "Sonstige"),
                        ],
                        default="custom",
                        max_length=100,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to="api.member",
                    ),
                ),
            ],
        ),
    ]
