# Generated by Django 4.2.4 on 2023-08-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_allergies_member_member_allergies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Allergies",
            new_name="Allergy",
        ),
    ]
