# Generated by Django 4.2.4 on 2023-08-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_member_allergies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="allergies",
            field=models.ManyToManyField(to="api.allergy"),
        ),
    ]
