# Generated by Django 4.2.4 on 2023-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_member_allergies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmedia",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
    ]
