# Generated by Django 4.2.4 on 2023-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_eventmedia_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="allergies",
            field=models.ManyToManyField(blank=True, to="api.allergy"),
        ),
    ]
