# Generated by Django 4.2.6 on 2023-10-08 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_eventmedia_mediaurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.PositiveIntegerField(blank=True, null=True)),
                ("month", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="from_day",
        ),
        migrations.RemoveField(
            model_name="event",
            name="from_month",
        ),
        migrations.RemoveField(
            model_name="event",
            name="from_year",
        ),
        migrations.RemoveField(
            model_name="event",
            name="to_day",
        ),
        migrations.RemoveField(
            model_name="event",
            name="to_month",
        ),
        migrations.AddField(
            model_name="event",
            name="from_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_events",
                to="api.customdate",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="to_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_events",
                to="api.customdate",
            ),
        ),
    ]
