# Generated by Django 4.2.6 on 2023-10-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customdate_remove_event_from_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday_members', to='api.customdate'),
        ),
        migrations.AddField(
            model_name='member',
            name='deathday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathday_members', to='api.customdate'),
        ),
    ]
