# Generated by Django 4.2.9 on 2024-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
