# Generated by Django 4.2.9 on 2024-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_registration_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signature',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
