# Generated by Django 4.2.9 on 2024-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_signature_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
